### ISSUE TITLE
Only First and Last PDF page get's affected by body style

### ISSUE THREAD

**Issue by ghost** [splitbrain/dokuwiki-plugin-dw2pdf#223]
Only the first and last page got the bar on the left(Even with bigger pdf with more than 3 sites).
I tryed everything I can but my Html/Css skills are limited.

Attached is an example and the style of my template

Hope you can help me :)

[online-anleitung (37).pdf](https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/files/134482/online-anleitung.37.pdf)

![style1](https://cloud.githubusercontent.com/assets/17296139/13112781/a349c306-d58c-11e5-83a7-77278853e888.PNG)
![style2](https://cloud.githubusercontent.com/assets/17296139/13112784/a5d2c686-d58c-11e5-96ee-2c9273ebf0cd.PNG)

**Comment by Klap-in** [comment]
Can you retest with the last version of dw2pdf?

**Comment by Klap-in** [comment]
And can you provide the style sheet as text, instead of a picture?

**Comment by Klap-in** [comment]
Using body style, I can reproduce the that the background image is only applied to first and last page of the document.

I have tested with 
```css
@page {
    background-image: url(lib/exe/fetch.php?media=picture.jpg);
    background-repeat: no-repeat;
    background-image-resize: 2;
}
```
This is showing backgrounds for every page. Please refer to https://mpdf.github.io/paging/using-page.html for more details about how to use it.
