### ISSUE TITLE
Changing the orientation within one document, the cover.html page template is used again

### ISSUE THREAD

**Issue by UMA-111** [splitbrain/dokuwiki-plugin-dw2pdf#501]
Hi there,

I tried to change the page orientation in one document by using:
```
~~PDF:LANDSCAPE~~
```
or
```
~~PDF:PORTRAIT~~
```
Whenever I do so, the cover.html from my DW2PDF template is used again.

Did I miss a way to prevent this, or is this a bug?

cheers,
UMA-111

**Comment by Klap-in** [comment]
Do you have an example of cover.html?

The PDF:landscape/portrait is somewhere in the wiki article which you are exporting?

**Comment by Klap-in** [comment]
After having a look. The cover can be just html like any other page, that is added before the normal pages are added. So far I know `<head>` and `<body>` tags are not needed. (I have not yet test with my own setup if it makes a difference). But I think it might be relevant thing to test out if removing them helps. Do not yet see other things that are remarkable for me.

**Comment by Klap-in** [comment]
Another thing to try out is the working of the `@page :first {   }` syntax.

```css
@page :first {
	header: _blank;
	footer: _blank;
	background-image: url(/lib/plugins/dw2pdf/tpl/yourtpl/cover_files/logo.jpg);
	background-repeat: no-repeat;
	background-image-resize: 1;
	background-position: 0% 25%;
}
```

It might be :first is used for each first page after rotating a page? Is probably not exactly how it should work, but maybe that is the culprit here? 
Alternatively, you can try to use your own named page instead of :first and add it to a css style you can refer from the div of the cover page? (see Named @page selectors).

https://mpdf.github.io/paging/using-page.html
